### ISSUE TITLE
About #3604 causing Clickhouse query to throw "Illegal column for DataTypeNullable" exception

### ISSUE THREAD

**Issue by klboke** [getsentry/snuba#3725] opened 2023-02-10 07:58 UTC
### Environment

- Sentry and snuba upgraded from 22.10.0 to 23.1.1
- Clickhouse version : 20.8.17.25

### Steps to Reproduce
Upgrade from 22.10.0 to 23.1.1, then visit the endpoint http://localhost:8000/organizations/sentry/releases/ 

### Expected Result

- Snuba's Clickhouse queries are error-free after upgrade

### Actual Result
Snuba Clickhouse queries will report the following exception ：
```python
QueryExecutionError: DB::Exception: Illegal column for DataTypeNullable. Stack trace:

0. /server/clickhouse_build/../contrib/poco/Foundation/src/Exception.cpp:27: Poco::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0x190f4af0 in /clickhouse/bin/clickhouse
1. /server/clickhouse_build/../src/Common/Exception.cpp:37: DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int) @ 0xe755f8d in /clickhouse/bin/clickhouse
2. /server/clickhouse_build/../contrib/libcxx/include/string:2134: DB::createBlockWithNestedColumnsImpl(DB::Block const&, std::__1::unordered_set<unsigned long, std::__1::hash<unsigned long>, std::__1::equal_to<unsigned long>, std::__1::allocator<unsigned long> > const&) (.cold) @ 0x15409b78 in /clickhouse/bin/clickhouse
3. /server/clickhouse_build/../contrib/libcxx/include/__hash_table:1541: DB::createBlockWithNestedColumns(DB::Block const&, std::__1::vector<unsigned long, std:...
  File "sentry/api/serializers/base.py", line 113, in _serialize
    return self.serialize(obj, attrs, user, **kwargs)
  File "sentry/api/serializers/models/event.py", line 369, in serialize
    result["release"] = self._get_release_info(user, obj)
  File "sentry/api/serializers/models/event.py", line 182, in _get_release_info
    return serialize(release, user)
  File "sentry/api/serializers/base.py", line 59, in serialize
    return serialize([objects], user=user, serializer=serializer, **kwargs)[0]
  File "sentry/api/serializers/base.py", line 75, in serialize
    attrs = serializer.get_attrs(
  File "sentry/api/serializers/models/release.py", line 347, in get_attrs
    first_seen, last_seen, issue_counts_by_release = self.__get_release_data_no_environment(
  File "sentry/api/serializers/models/release.py", line 245, in __get_release_data_no_environment
    tag_values = tagstore.get_release_tags(
  File "sentry/utils/services.py", line 127, in <lambda>
    context[key] = (lambda f: lambda *a, **k: getattr(self, f)(*a, **k))(key)
  File "sentry/tagstore/snuba/backend.py", line 740, in get_release_tags
    result = snuba.query(
  File "sentry/utils/snuba.py", line 986, in query
    body = raw_query(
  File "sentry/utils/snuba.py", line 725, in raw_query
    return bulk_raw_query([snuba_params], referrer=referrer, use_cache=use_cache)[0]
  File "sentry/utils/snuba.py", line 776, in bulk_raw_query
    return _apply_cache_and_build_results(params, referrer=referrer, use_cache=use_cache)
  File "sentry/utils/snuba.py", line 811, in _apply_cache_and_build_results
    query_results = _bulk_snuba_query([item[1] for item in to_query], headers)
  File "sentry/utils/snuba.py", line 894, in _bulk_snuba_query
    raise clickhouse_error_codes_map.get(error["code"], QueryExecutionError)(
```
The query SQL is as follows
```sql
SELECT
	(project_id AS _snuba_project_id),
	(release AS `_snuba_tags[sentry:release]`),
	(count() AS _snuba_times_seen),
	(min((timestamp AS _snuba_timestamp)) AS _snuba_first_seen),
	(max(_snuba_timestamp) AS _snuba_last_seen)
FROM
	errors_local PREWHERE in(`_snuba_tags[sentry:release]`, tuple('com.xx@2.43.1-mkt.100000'))
WHERE
	equals(deleted,
	0)
	AND greaterOrEquals(_snuba_timestamp,
	toDateTime('2023-02-06T08:09:35',
	'Universal'))
	AND less(_snuba_timestamp,
	toDateTime('2023-02-09T23:07:26',
	'Universal'))
	AND in(_snuba_project_id, tuple(148))
	AND 1
	AND in(_snuba_project_id, tuple(148))
GROUP BY
	_snuba_project_id,
	`_snuba_tags[sentry:release]`
ORDER BY
	_snuba_times_seen DESC
LIMIT 1000 OFFSET 0
```

### Analysis of the problem
This is related to https://github.com/getsentry/snuba/pull/3604 submitted by @dbanda , and I hope to get your answer. This pr creates three indexes like:
```sql
ALTER TABLE errors_local ADD INDEX IF NOT EXISTS bf_tags_hash_map _tags_hash_map TYPE bloom_filter GRANULARITY 1;
ALTER TABLE errors_local ADD INDEX IF NOT EXISTS minmax_group_id group_id TYPE minmax GRANULARITY 1;
ALTER TABLE errors_local ADD INDEX IF NOT EXISTS bf_release release TYPE bloom_filter GRANULARITY 1;
```
Because all query exceptions "Illegal column for DataTypeNullable" are related to the errors_local table, and the main DDL change from 22.10.0 to 23.1.1 is the above three indexes, so when I try to delete the index through the following script, The Clickhouse query of Snuba version 23.1.1 is also all normal
```shell
snuba migrations reverse --group=events --migration-id=0018_errors_ro_add_tags_hash_map --force --log-level=debug
snuba migrations reverse --group=events --migration-id=0017_errors_add_indexes --force --log-level=debug
```

**Comment by dbanda** [comment] 2023-02-14 20:50
what version of Clickhouse are you running?

**Comment by fpacifici** [comment] 2023-02-14 21:37
@dbanda  This errors sounds a lot like something on the query pipeline in clickhouse that does not work on a nullable column. 
The migrations added a bloomfilter index on the `sentry:release`  column which is nullable and it is the only nullable column in the query is that column. 
Once we know the clickhouse version we can try to reproduce by querying the nullable column with an index. 
If that turns out to be the problem (likely a clickhouse bug on that version) indexes can be disabled on specific queries `use_skip_indexes` setting https://clickhouse.com/docs/en/operations/settings/settings/#settings-use_skip_indexes. I think this setting can be set on the fly when running the query.

**Comment by klboke** [comment] 2023-02-15 05:04
> what version of Clickhouse are you running?

Clickhouse version : `20.8.17.25`

**Comment by ntcong** [comment] 2023-02-16 05:11
The default helm chart with clickhouse version "yandex/clickhouse-server:20.8.19.4" also has this problem.

**Comment by klboke** [comment] 2023-02-27 06:28
@dbanda  Hello, has there been any progress on this issue yet?

**Comment by dbanda** [comment] 2023-03-05 10:30
It a Clickhouse bug see: https://github.com/getsentry/sentry/issues/45306. It looks like is specific to that version and can be fixed by upgrading. There was a bug in the coalesce function.

**Closed** 2023-03-05 10:31 UTC
Labels: Status: Needs More Information
